version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"

- package-ecosystem: "nuget" 
  directory: "/"
  schedule:
    interval: "weekly"

- package-ecosystem: "docker" 
  directory: "/"
  schedule:
    interval: "weekly"
  ignore:
  - dependency-name: "*"
    update-types: ["version-update:semver-major"]
