# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Java

# permissions:
#   checks: write # Required for jacoco-reporter
#   pull-requests: write # Required for jacoco-reporter
#   packages: write # Required for Docker
#   contents: read # Required for jacoco-reporter
#   security-events: write # Required for Trivy

on:
  push:
    branches:
      - "main"
      - "feature/actions"
  pull_request:
    branches:
      - "main"

jobs:
  build-java-workflow:
    permissions:
      checks: write # Required for jacoco-reporter
      pull-requests: write # Required for jacoco-reporter
      contents: read # Required for jacoco-reporter
    uses: artm-devsec-ops/.github/workflow-templates/artm-devsecops-build-java.yml@main
    with:
      java_version: 17
      fail_below_threshold: false

  build-image-workflow:
    permissions:
      packages: write # Required for Container
      security-events: write # Required for Scanning
    uses: artm-devsec-ops/.github/workflow-templates/artm-devsecops-build-image.yml@main
    with:
      image_tag: "v1"
      image_context: "./target"
      image_files: "ContainerFile"
      container_registry: "ghcr.io"
      scan_offline: true
