# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Java

on:
  push:
    branches: 
      - "main"
      - "feature/actions"
  pull_request:
    branches: 
      - "main"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Restore dependencies
      run: mvn dependency:resolve

    - name: Tests
      run: mvn --batch-mode --update-snapshots verify test package
