name: Java

on:
  push:
    branches:
      - "main"
      - "feature/actions"
  pull_request:
    branches:
      - "main"

jobs:
  build-java-workflow:
    name: "Build application"
    permissions:
      checks: write # Required for jacoco-reporter
      pull-requests: write # Required for jacoco-reporter
      contents: read # Required for jacoco-reporter
    uses: artm-devsecops/artm-workflow-templates/.github/workflows/artm-devsecops-build-java.yml@main
    with:
      java_version: 17
      fail_below_threshold: false

  build-image-workflow:
    name: "Build image"
    needs: build-java-workflow
    permissions:
      packages: write # Required for Container
      security-events: write # Required for Scanning
    uses: artm-devsecops/artm-workflow-templates/.github/workflows/artm-devsecops-build-image.yml@main
    with:
      image_tag: "v1"
      image_context: "./target"
      image_files: "ContainerFile"
      container_registry: "ghcr.io"
      scan_offline: true
